# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yhpark', '0004_auto_20170621_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_file',
        ),
    ]
